export const BARBER_LOGGED_IN_MIDDLEWARE_SUCCESS = "BARBER_LOGGED_IN_MIDDLEWARE_SUCCESS"

//AFTER SUCCESSFUL SIGNIN THIS MIDDLEWARE IS CALLING AND IS RESPONSIBLE FOR GIBING CURRENT ADMIN DATA
export const BARBER_GOOGLE_SIGNIN_REQ = "BARBER_GOOGLE_SIGNIN_REQ"
export const BARBER_GOOGLE_SIGNIN_SUCCESS = "BARBER_GOOGLE_SIGNIN_SUCCESS"
export const BARBER_GOOGLE_SIGNIN_FAIL = "BARBER_GOOGLE_SIGNIN_FAIL"

export const BARBER_GOOGLE_SIGNUP_REQ = "BARBER_GOOGLE_SIGNUP_REQ"
export const BARBER_GOOGLE_SIGNUP_SUCCESS = "BARBER_GOOGLE_SIGNUP_SUCCESS"
export const BARBER_GOOGLE_SIGNUP_FAIL = "BARBER_GOOGLE_SIGNUP_FAIL"

export const BARBER_SIGNUP_REQ = "BARBER_SIGNUP_REQ"
export const BARBER_SIGNUP_SUCCESS = "BARBER_SIGNUP_SUCCESS"
export const BARBER_SIGNUP_FAIL = "BARBER_SIGNUP_FAIL"

export const BARBER_SIGNIN_REQ = "BARBER_SIGNIN_REQ"
export const BARBER_SIGNIN_SUCCESS = "BARBER_SIGNIN_SUCCESS"
export const BARBER_SIGNIN_FAIL = "BARBER_SIGNIN_FAIL"

export const BARBER_SIGNUP_EDIT_REQ = "BARBER_SIGNUP_EDIT_REQ"
export const BARBER_SIGNUP_EDIT_SUCCESS = "BARBER_SIGNUP_EDIT_SUCCESS"
export const BARBER_SIGNUP_EDIT_FAIL = "BARBER_SIGNUP_EDIT_FAIL"

export const BARBER_LOGOUT_REQ = "BARBER_LOGOUT_REQ"
export const BARBER_LOGOUT_SUCCESS = "BARBER_LOGOUT_SUCCESS"
export const BARBER_LOGOUT_FAIL = "BARBER_LOGOUT_FAIL"

export const CONNECT_SALON_LIST_REQ = "CONNECT_SALON_LIST_REQ"
export const CONNECT_SALON_LIST_SUCCESS = "CONNECT_SALON_LIST_SUCCESS"
export const CONNECT_SALON_LIST_FAIL = "CONNECT_SALON_LIST_FAIL"

export const BARBER_CONNECT_SALON_REQ = "BARBER_CONNECT_SALON_REQ"
export const BARBER_CONNECT_SALON_SUCCESS = "BARBER_CONNECT_SALON_SUCCESS"
export const BARBER_CONNECT_SALON_FAIL = "BARBER_CONNECT_SALON_FAIL"

export const BARBER_FORGET_PASSWORD_REQ = "BARBER_FORGET_PASSWORD_REQ"
export const BARBER_FORGET_PASSWORD_SUCCESS = "BARBER_FORGET_PASSWORD_SUCCESS"
export const BARBER_FORGET_PASSWORD_FAIL = "BARBER_FORGET_PASSWORD_FAIL"

export const BARBER_RESET_PASSWORD_REQ = "BARBER_RESET_PASSWORD_REQ"
export const BARBER_RESET_PASSWORD_SUCCESS = "BARBER_RESET_PASSWORD_SUCCESS"
export const BARBER_RESET_PASSWORD_FAIL = "BARBER_RESET_PASSWORD_FAIL"

export const GET_QUEUELIST_BARBERID_REQ = "GET_QUEUELIST_BARBERID_REQ"
export const GET_QUEUELIST_BARBERID_SUCCESS = "GET_QUEUELIST_BARBERID_SUCCESS"
export const GET_QUEUELIST_BARBERID_FAIL = "GET_QUEUELIST_BARBERID_FAIL"

export const BARBER_UPDATE_PROFILE_REQ = "BARBER_UPDATE_PROFILE_REQ"
export const BARBER_UPDATE_PROFILE_SUCCESS = "BARBER_UPDATE_PROFILE_SUCCESS"
export const BARBER_UPDATE_PROFILE_FAIL = "BARBER_UPDATE_PROFILE_FAIL"

export const BARBER_SKIP_PROFILE_REQ = "BARBER_SKIP_PROFILE_REQ"
export const BARBER_SKIP_PROFILE_SUCCESS = "BARBER_SKIP_PROFILE_SUCCESS"
export const BARBER_SKIP_PROFILE_FAIL = "BARBER_SKIP_PROFILE_FAIL"

export const BARBER_SEND_VERIFY_EMAIL_REQ = "BARBER_SEND_VERIFY_EMAIL_REQ"
export const BARBER_SEND_VERIFY_EMAIL_SUCCESS = "BARBER_SEND_VERIFY_EMAIL_SUCCESS"
export const BARBER_SEND_VERIFY_EMAIL_FAIL = "BARBER_SEND_VERIFY_EMAIL_FAIL"

export const BARBER_SEND_VERIFY_MOBILE_REQ = "BARBER_SEND_VERIFY_MOBILE_REQ"
export const BARBER_SEND_VERIFY_MOBILE_SUCCESS = "BARBER_SEND_VERIFY_MOBILE_SUCCESS"
export const BARBER_SEND_VERIFY_MOBILE_FAIL = "BARBER_SEND_VERIFY_MOBILE_FAIL"

export const BARBER_VERIFIED_EMAIL_STATUS_REQ = "BARBER_VERIFIED_EMAIL_STATUS_REQ"
export const BARBER_VERIFIED_EMAIL_STATUS_SUCCESS = "BARBER_VERIFIED_EMAIL_STATUS_SUCCESS"
export const BARBER_VERIFIED_EMAIL_STATUS_FAIL = "BARBER_VERIFIED_EMAIL_STATUS_FAIL"

export const BARBER_VERIFIED_MOBILE_STATUS_REQ = "BARBER_VERIFIED_MOBILE_STATUS_REQ"
export const BARBER_VERIFIED_MOBILE_STATUS_SUCCESS = "BARBER_VERIFIED_MOBILE_STATUS_SUCCESS"
export const BARBER_VERIFIED_MOBILE_STATUS_FAIL = "BARBER_VERIFIED_MOBILE_STATUS_FAIL"

export const CHANGE_BARBER_ONLINESTATUS_REQ = "CHANGE_BARBER_ONLINESTATUS_REQ"
export const CHANGE_BARBER_ONLINESTATUS_SUCCESS = "CHANGE_BARBER_ONLINESTATUS_SUCCESS"
export const CHANGE_BARBER_ONLINESTATUS_FAIL = "CHANGE_BARBER_ONLINESTATUS_FAIL"

export const GET_BARBER_SALON_LOGO_REQ = "GET_BARBER_SALON_LOGO_REQ"
export const GET_BARBER_SALON_LOGO_SUCCESS = "GET_BARBER_SALON_LOGO_SUCCESS"
export const GET_BARBER_SALON_LOGO_FAIL = "GET_BARBER_SALON_LOGO_FAIL"

export const BARBER_DASHBOARD_SALON_INFO_REQ = "BARBER_DASHBOARD_SALON_INFO_REQ"
export const BARBER_DASHBOARD_SALON_INFO_SUCCESS = "BARBER_DASHBOARD_SALON_INFO_SUCCESS"
export const BARBER_DASHBOARD_SALON_INFO_FAIL = "BARBER_DASHBOARD_SALON_INFO_FAIL"

export const GET_BARBER_ALL_CUSTOMERLIST_REQ = "GET_BARBER_ALL_CUSTOMERLIST_REQ"
export const GET_BARBER_ALL_CUSTOMERLIST_SUCCESS = "GET_BARBER_ALL_CUSTOMERLIST_SUCCESS"
export const GET_BARBER_ALL_CUSTOMERLIST_FAIL = "GET_BARBER_ALL_CUSTOMERLIST_FAIL"


export const BARBER_BARBER_SERVED_QUEUE_REQ = "BARBER_BARBER_SERVED_QUEUE_REQ"
export const BARBER_BARBER_SERVED_QUEUE_SUCCESS = "BARBER_BARBER_SERVED_QUEUE_SUCCESS"
export const BARBER_BARBER_SERVED_QUEUE_FAIL = "BARBER_BARBER_SERVED_QUEUE_FAIL"

export const BARBER_CANCEL_QUEUE_REQ = "BARBER_CANCEL_QUEUE_REQ"
export const BARBER_CANCEL_QUEUE_SUCCESS = "BARBER_CANCEL_QUEUE_SUCCESS"
export const BARBER_CANCEL_QUEUE_FAIL = "BARBER_CANCEL_QUEUE_FAIL"

export const BARBER_UPDATE_PASSWORD_REQ = "BARBER_UPDATE_PASSWORD_REQ"
export const BARBER_UPDATE_PASSWORD_SUCCESS = "BARBER_UPDATE_PASSWORD_SUCCESS"
export const BARBER_UPDATE_PASSWORD_FAIL = "BARBER_UPDATE_PASSWORD_FAIL"

export const BARBER_SEND_CUSTOMER_MAIL_REQ = "BARBER_SEND_CUSTOMER_MAIL_REQ"
export const BARBER_SEND_CUSTOMER_MAIL_SUCCESS = "BARBER_SEND_CUSTOMER_MAIL_SUCCESS"
export const BARBER_SEND_CUSTOMER_MAIL_FAIL = "BARBER_SEND_CUSTOMER_MAIL_FAIL"

export const BARBER_SEND_CUSTOMER_MESSAGE_REQ = "BARBER_SEND_CUSTOMER_MESSAGE_REQ"
export const BARBER_SEND_CUSTOMER_MESSAGE_SUCCESS = "BARBER_SEND_CUSTOMER_MESSAGE_SUCCESS"
export const BARBER_SEND_CUSTOMER_MESSAGE_FAIL = "BARBER_SEND_CUSTOMER_MAIL_FAIL"

export const GET_QUEUE_HISTORY_REQ = "GET_QUEUE_HISTORY_REQ"
export const GET_QUEUE_HISTORY_SUCCESS = "GET_QUEUE_HISTORY_SUCCESS"
export const GET_QUEUE_HISTORY_FAIL = "GET_QUEUE_HISTORY_FAIL"

export const GET_ALL_SALON_SERVICES_REQ = "GET_ALL_SALON_SERVICES_REQ"
export const GET_ALL_SALON_SERVICES_SUCCESS = "GET_ALL_SALON_SERVICES_SUCCESS"
export const GET_ALL_SALON_SERVICES_FAIL = "GET_ALL_SALON_SERVICES_FAIL"

export const GET_BARBER_APPOINT_LIST_REQ = "GET_BARBER_APPOINT_LIST_REQ"
export const GET_BARBER_APPOINT_LIST_SUCCESS = "GET_BARBER_APPOINT_LIST_SUCCESS"
export const GET_BARBER_APPOINT_LIST_FAIL = "GET_BARBER_APPOINT_LIST_FAIL"

export const CANCEL_APPOINT_REQ = "CANCEL_APPOINT_REQ"
export const CANCEL_APPOINT_SUCCESS = "CANCEL_APPOINT_SUCCESS"
export const CANCEL_APPOINT_FAIL = "CANCEL_APPOINT_FAIL"

export const SERVE_APPOINT_REQ = "SERVE_APPOINT_REQ"
export const SERVE_APPOINT_SUCCESS = "SERVE_APPOINT_SUCCESS"
export const SERVE_APPOINT_FAIL = "SERVE_APPOINT_FAIL"

export const GET_APPOINTMENT_HISTORY_REQ = "GET_APPOINTMENT_HISTORY_REQ"
export const GET_APPOINTMENT_HISTORY_SUCCESS = "GET_APPOINTMENT_HISTORY_SUCCESS"
export const GET_APPOINTMENT_HISTORY_FAIL = "GET_APPOINTMENT_HISTORY_FAIL"

export const GET_APPOINTMENT_LIST_BARBERID_APPOINTMENT_REQ = "GET_APPOINTMENT_LIST_BARBERID_APPOINTMENT_REQ"
export const GET_APPOINTMENT_LIST_BARBERID_APPOINTMENT_SUCCESS = "GET_APPOINTMENT_LIST_BARBERID_APPOINTMENT_SUCCESS"
export const GET_APPOINTMENT_LIST_BARBERID_APPOINTMENT_FAIL = "GET_APPOINTMENT_LIST_BARBERID_APPOINTMENT_FAIL"