export const ADMIN_GOOGLE_SIGNIN_REQ = "ADMIN_GOOGLE_SIGNIN_REQ"
export const ADMIN_GOOGLE_SIGNIN_SUCCESS = "ADMIN_GOOGLE_SIGNIN_SUCCESS"
export const ADMIN_GOOGLE_SIGNIN_FAIL = "ADMIN_GOOGLE_SIGNIN_FAIL"

export const ADMIN_GOOGLE_SIGNUP_REQ = "ADMIN_GOOGLE_SIGNUP_REQ"
export const ADMIN_GOOGLE_SIGNUP_SUCCESS = "ADMIN_GOOGLE_SIGNUP_SUCCESS"
export const ADMIN_GOOGLE_SIGNUP_FAIL = "ADMIN_GOOGLE_SIGNUP_FAIL"

export const ADMIN_SIGNUP_REQ = "ADMIN_SIGNUP_REQ"
export const ADMIN_SIGNUP_SUCCESS = "ADMIN_SIGNUP_SUCCESS"
export const ADMIN_SIGNUP_FAIL = "ADMIN_SIGNUP_FAIL"

export const ADMIN_SIGNIN_REQ = "ADMIN_SIGNIN_REQ"
export const ADMIN_SIGNIN_SUCCESS = "ADMIN_SIGNIN_SUCCESS"
export const ADMIN_SIGNIN_FAIL = "ADMIN_SIGNIN_FAIL"

export const ADMIN_SIGNUP_EDIT_REQ = "ADMIN_SIGNUP_EDIT_REQ"
export const ADMIN_SIGNUP_EDIT_SUCCESS = "ADMIN_SIGNUP_EDIT_SUCCESS"
export const ADMIN_SIGNUP_EDIT_FAIL = "ADMIN_SIGNUP_EDIT_FAIL"

//AFTER SUCCESSFUL SIGNIN THIS MIDDLEWARE IS CALLING AND IS RESPONSIBLE FOR GIVING CURRENT ADMIN DATA
export const ADMIN_LOGGED_IN_MIDDLEWARE_SUCCESS = "ADMIN_LOGGED_IN_MIDDLEWARE_SUCCESS"

export const ADMIN_LOGOUT_REQ = "ADMIN_LOGOUT_REQ"
export const ADMIN_LOGOUT_SUCCESS = "ADMIN_LOGOUT_SUCCESS"
export const ADMIN_LOGOUT_FAIL = "ADMIN_LOGOUT_FAIL"

export const GET_ALL_ADVERTISEMENT_REQ = "GET_ALL_ADVERTISEMENT_REQ"
export const GET_ALL_ADVERTISEMENT_SUCCESS = "GET_ALL_ADVERTISEMENT_SUCCESS"
export const GET_ALL_ADVERTISEMENT_FAIL = "GET_ALL_ADVERTISEMENT_FAIL"

export const GET_ALL_QUEUELIST_REQ = "GET_ALL_QUEUELIST_REQ"
export const GET_ALL_QUEUELIST_SUCCESS = "GET_ALL_QUEUELIST_SUCCESS"
export const GET_ALL_QUEUELIST_FAIL = "GET_ALL_QUEUELIST_FAIL"

export const GET_DASHBOARD_APPOINTMENT_LIST_REQ = "GET_DASHBOARD_APPOINTMENT_LIST_REQ"
export const GET_DASHBOARD_APPOINTMENT_LIST_SUCCESS = "GET_DASHBOARD_APPOINTMENT_LIST_SUCCESS"
export const GET_DASHBOARD_APPOINTMENT_LIST_FAIL = "GET_DASHBOARD_APPOINTMENT_LIST_FAIL"

export const GET_ADMIN_SALONLIST_REQ = "GET_ADMIN_SALONLIST_REQ"
export const GET_ADMIN_SALONLIST_SUCCESS = "GET_ADMIN_SALONLIST_SUCCESS"
export const GET_ADMIN_SALONLIST_FAIL = "GET_ADMIN_SALONLIST_FAIL"

export const GET_ADMIN_BARBERLIST_REQ = "GET_ADMIN_BARBERLIST_REQ"
export const GET_ADMIN_BARBERLIST_SUCCESS = "GET_ADMIN_BARBERLIST_SUCCESS"
export const GET_ADMIN_BARBERLIST_FAIL = "GET_ADMIN_BARBERLIST_FAIL"

export const CHANGE_ADMIN_BARBER_ONLINESTATUS_REQ = "CHANGE_ADMIN_BARBER_ONLINESTATUS_REQ"
export const CHANGE_ADMIN_BARBER_ONLINESTATUS_SUCCESS = "CHANGE_ADMIN_BARBER_ONLINESTATUS_SUCCESS"
export const CHANGE_ADMIN_BARBER_ONLINESTATUS_FAIL = "CHANGE_ADMIN_BARBER_ONLINESTATUS_FAIL"

export const CHANGE_ADMIN_BARBER_CLOCKSTATUS_REQ = "CHANGE_ADMIN_BARBER_CLOCKSTATUS_REQ"
export const CHANGE_ADMIN_BARBER_CLOCKSTATUS_SUCCESS = "CHANGE_ADMIN_BARBER_CLOCKSTATUS_SUCCESS"
export const CHANGE_ADMIN_BARBER_CLOCKSTATUS_FAIL = "CHANGE_ADMIN_BARBER_CLOCKSTATUS_FAIL"

export const ADMIN_APPROVE_BARBER_REQ = "ADMIN_APPROVE_BARBER_REQ"
export const ADMIN_APPROVE_BARBER_SUCCESS = "ADMIN_APPROVE_BARBER_SUCCESS"
export const ADMIN_APPROVE_BARBER_FAIL = "ADMIN_APPROVE_BARBER_FAIL"

export const ADMIN_ALL_SALON_SERVICES_REQ = "ADMIN_ALL_SALON_SERVICES_REQ"
export const ADMIN_ALL_SALON_SERVICES_SUCCESS = "ADMIN_ALL_SALON_SERVICES_SUCCESS"
export const ADMIN_ALL_SALON_SERVICES_FAIL = "ADMIN_ALL_SALON_SERVICES_FAIL"

export const ADMIN_CREATE_BARBER_REQ = "ADMIN_CREATE_BARBER_REQ"
export const ADMIN_CREATE_BARBER_SUCCESS = "ADMIN_CREATE_BARBER_SUCCESS"
export const ADMIN_CREATE_BARBER_FAIL = "ADMIN_CREATE_BARBER_FAIL"

export const ADMIN_UPDATE_BARBER_REQ = "ADMIN_UPDATE_BARBER_REQ"
export const ADMIN_UPDATE_BARBER_SUCCESS = "ADMIN_UPDATE_BARBER_SUCCESS"
export const ADMIN_UPDATE_BARBER_FAIL = "ADMIN_UPDATE_BARBER_FAIL"

export const ADMIN_DELETE_BARBER_REQ = "ADMIN_DELETE_BARBER_REQ"
export const ADMIN_DELETE_BARBER_SUCCESS = "ADMIN_DELETE_BARBER_SUCCESS"
export const ADMIN_DELETE_BARBER_FAIL = "ADMIN_DELETE_BARBER_FAIL"

export const ADMIN_GETALLSALON_ICONS_REQ = "ADMIN_GETALLSALON_ICONS_REQ"
export const ADMIN_GETALLSALON_ICONS_SUCCESS = "ADMIN_GETALLSALON_ICONS_SUCCESS"
export const ADMIN_GETALLSALON_ICONS_FAIL = "ADMIN_GETALLSALON_ICONS_FAIL"

export const ADMIN_GET_ALL_COUNTRIES_REQ = "ADMIN_GET_ALL_COUNTRIES_REQ"
export const ADMIN_GET_ALL_COUNTRIES_SUCCESS = "ADMIN_GET_ALL_COUNTRIES_SUCCESS"
export const ADMIN_GET_ALL_COUNTRIES_FAIL = "ADMIN_GET_ALL_COUNTRIES_FAIL"

export const ADMIN_GET_ALL_CITIES_REQ = "ADMIN_GET_ALL_CITIES_REQ"
export const ADMIN_GET_ALL_CITIES_SUCCESS = "ADMIN_GET_ALL_CITIES_SUCCESS"
export const ADMIN_GET_ALL_CITIES_FAIL = "ADMIN_GET_ALL_CITIES_FAIL"

export const ADMIN_GET_ALL_TIMEZONES_REQ = "ADMIN_GET_ALL_TIMEZONES_REQ"
export const ADMIN_GET_ALL_TIMEZONES_SUCCESS = "ADMIN_GET_ALL_TIMEZONES_SUCCESS"
export const ADMIN_GET_ALL_TIMEZONES_FAIL = "ADMIN_GET_ALL_TIMEZONES_FAIL"

export const ADMIN_DELETE_SALON_REQ = "ADMIN_DELETE_SALON_REQ"
export const ADMIN_DELETE_SALON_SUCCESS = "ADMIN_DELETE_SALON_SUCCESS"
export const ADMIN_DELETE_SALON_FAIL = "ADMIN_DELETE_SALON_FAIL"

export const ADMIN_CREATE_SALON_REQ = "ADMIN_CREATE_SALON_REQ"
export const ADMIN_CREATE_SALON_SUCCESS = "ADMIN_CREATE_SALON_SUCCESS"
export const ADMIN_CREATE_SALON_FAIL = "ADMIN_CREATE_SALON_FAIL"

export const ADMIN_EDIT_SALON_REQ = "ADMIN_EDIT_SALON_REQ"
export const ADMIN_EDIT_SALON_SUCCESS = "ADMIN_EDIT_SALON_SUCCESS"
export const ADMIN_EDIT_SALON_FAIL = "ADMIN_EDIT_SALON_FAIL"

export const ADMIN_UPDATE_PROFILE_REQ = "ADMIN_UPDATE_PROFILE_REQ"
export const ADMIN_UPDATE_PROFILE_SUCCESS = "ADMIN_UPDATE_PROFILE_SUCCESS"
export const ADMIN_UPDATE_PROFILE_FAIL = "ADMIN_UPDATE_PROFILE_FAIL"

export const ADMIN_SKIP_PROFILE_REQ = "ADMIN_SKIP_PROFILE_REQ"
export const ADMIN_SKIP_PROFILE_SUCCESS = "ADMIN_SKIP_PROFILE_SUCCESS"
export const ADMIN_SKIP_PROFILE_FAIL = "ADMIN_SKIP_PROFILE_FAIL"

export const GET_ALL_CUSTOMERLIST_REQ = "GET_ALL_CUSTOMERLIST_REQ"
export const GET_ALL_CUSTOMERLIST_SUCCESS = "GET_ALL_CUSTOMERLIST_SUCCESS"
export const GET_ALL_CUSTOMERLIST_FAIL = "GET_ALL_CUSTOMERLIST_FAIL"

export const ADMIN_BARBER_SERVED_QUEUE_REQ = "ADMIN_BARBER_SERVED_QUEUE_REQ"
export const ADMIN_BARBER_SERVED_QUEUE_SUCCESS = "ADMIN_BARBER_SERVED_QUEUE_SUCCESS"
export const ADMIN_BARBER_SERVED_QUEUE_FAIL = "ADMIN_BARBER_SERVED_QUEUE_FAIL"

export const ADMIN_CANCEL_QUEUE_REQ = "ADMIN_CANCEL_QUEUE_REQ"
export const ADMIN_CANCEL_QUEUE_SUCCESS = "ADMIN_CANCEL_QUEUE_SUCCESS"
export const ADMIN_CANCEL_QUEUE_FAIL = "ADMIN_CANCEL_QUEUE_FAIL"

export const ADMIN_SEND_VERIFY_EMAIL_REQ = "ADMIN_SEND_VERIFY_EMAIL_REQ"
export const ADMIN_SEND_VERIFY_EMAIL_SUCCESS = "ADMIN_SEND_VERIFY_EMAIL_SUCCESS"
export const ADMIN_SEND_VERIFY_EMAIL_FAIL = "ADMIN_SEND_VERIFY_EMAIL_FAIL"

export const ADMIN_SEND_VERIFY_MOBILE_REQ = "ADMIN_SEND_VERIFY_MOBILE_REQ"
export const ADMIN_SEND_VERIFY_MOBILE_SUCCESS = "ADMIN_SEND_VERIFY_MOBILE_SUCCESS"
export const ADMIN_SEND_VERIFY_MOBILE_FAIL = "ADMIN_SEND_VERIFY_MOBILE_FAIL"

export const ADMIN_VERIFIED_EMAIL_STATUS_REQ = "ADMIN_VERIFIED_EMAIL_STATUS_REQ"
export const ADMIN_VERIFIED_EMAIL_STATUS_SUCCESS = "ADMIN_VERIFIED_EMAIL_STATUS_SUCCESS"
export const ADMIN_VERIFIED_EMAIL_STATUS_FAIL = "ADMIN_VERIFIED_EMAIL_STATUS_FAIL"

export const ADMIN_VERIFIED_MOBILE_STATUS_REQ = "ADMIN_VERIFIED_MOBILE_STATUS_REQ"
export const ADMIN_VERIFIED_MOBILE_STATUS_SUCCESS = "ADMIN_VERIFIED_MOBILE_STATUS_SUCCESS"
export const ADMIN_VERIFIED_MOBILE_STATUS_FAIL = "ADMIN_VERIFIED_MOBILE_STATUS_FAIL"

export const ADMIN_APPLY_SALON_REQ = "ADMIN_APPLY_SALON_REQ"
export const ADMIN_APPLY_SALON_SUCCESS = "ADMIN_APPLY_SALON_SUCCESS"
export const ADMIN_APPLY_SALON_FAIL = "ADMIN_APPLY_SALON_FAIL"

export const ADMIN_GET_DEFAULT_SALON_REQ = "ADMIN_GET_DEFAULT_SALON_REQ"
export const ADMIN_GET_DEFAULT_SALON_SUCCESS = "ADMIN_GET_DEFAULT_SALON_SUCCESS"
export const ADMIN_GET_DEFAULT_SALON_FAIL = "ADMIN_GET_DEFAULT_SALON_FAIL"

export const SALON_ONLINE_STATUS_REQ = "SALON_ONLINE_STATUS_REQ"
export const SALON_ONLINE_STATUS_SUCCESS = "SALON_ONLINE_STATUS_SUCCESS"
export const SALON_ONLINE_STATUS_FAIL = "SALON_ONLINE_STATUS_FAIL"

export const ADMIN_UPDATE_SALON_SETTINGS_REQ = "ADMIN_UPDATE_SALON_SETTINGS_REQ"
export const ADMIN_UPDATE_SALON_SETTINGS_SUCCESS = "ADMIN_UPDATE_SALON_SETTINGS_SUCCESS"
export const ADMIN_UPDATE_SALON_SETTINGS_FAIL = "ADMIN_UPDATE_SALON_SETTINGS_FAIL"

export const ADMIN_FORGET_PASSWORD_REQ = "ADMIN_FORGET_PASSWORD_REQ"
export const ADMIN_FORGET_PASSWORD_SUCCESS = "ADMIN_FORGET_PASSWORD_SUCCESS"
export const ADMIN_FORGET_PASSWORD_FAIL = "ADMIN_FORGET_PASSWORD_FAIL"

export const ADMIN_RESET_PASSWORD_REQ = "ADMIN_RESET_PASSWORD_REQ"
export const ADMIN_RESET_PASSWORD_SUCCESS = "ADMIN_RESET_PASSWORD_SUCCESS"
export const ADMIN_RESET_PASSWORD_FAIL = "ADMIN_RESET_PASSWORD_FAIL"

export const ADMIN_UPLOAD_PROFILE_PIC_REQ = "ADMIN_UPLOAD_PROFILE_PIC_REQ"
export const ADMIN_UPLOAD_PROFILE_PIC_SUCCESS = "ADMIN_UPLOAD_PROFILE_PIC_SUCCESS"
export const ADMIN_UPLOAD_PROFILE_PIC_FAIL = "ADMIN_UPLOAD_PROFILE_PIC_FAIL"

export const ADMIN_UPDATE_SALON_INFO_REQ = "ADMIN_UPDATE_SALON_INFO_REQ"
export const ADMIN_UPDATE_SALON_INFO_SUCCESS = "ADMIN_UPDATE_SALON_INFO_SUCCESS"
export const ADMIN_UPDATE_SALON_INFO_FAIL = "ADMIN_UPDATE_SALON_INFO_FAIL"

export const DARK_MODE_ON = "DARK_MODE_ON"
export const DARK_MODE_OFF = "DARK_MODE_OFF"

export const ADMIN_GET_SALON_IMAGES_REQ = "ADMIN_GET_SALON_IMAGES_REQ"
export const ADMIN_GET_SALON_IMAGES_SUCCESS = "ADMIN_GET_SALON_IMAGES_SUCCESS"
export const ADMIN_GET_SALON_IMAGES_FAIL = "ADMIN_GET_SALON_IMAGES_FAIL"

export const ADMIN_GET_SALON_LOGO_REQ = "ADMIN_GET_SALON_LOGO_REQ"
export const ADMIN_GET_SALON_LOGO_SUCCESS = "ADMIN_GET_SALON_LOGO_SUCCESS"
export const ADMIN_GET_SALON_LOGO_FAIL = "ADMIN_GET_SALON_LOGO_FAIL"

export const ADMIN_DRAG_ADVERTISEMENT_REQ = "ADMIN_DRAG_ADVERTISEMENT_REQ"
export const ADMIN_DRAG_ADVERTISEMENT_SUCCESS = "ADMIN_DRAG_ADVERTISEMENT_SUCCESS"
export const ADMIN_DRAG_ADVERTISEMENT_FAIL = "ADMIN_DRAG_ADVERTISEMENT_FAIL"

export const ADMIN_SEND_BARBER_MAIL_REQ = "ADMIN_SEND_BARBER_MAIL_REQ"
export const ADMIN_SEND_BARBER_MAIL_SUCCESS = "ADMIN_SEND_BARBER_MAIL_SUCCESS"
export const ADMIN_SEND_BARBER_MAIL_FAIL = "ADMIN_SEND_BARBER_MAIL_FAIL"

export const ADMIN_SEND_BARBER_MESSAGE_REQ = "ADMIN_SEND_BARBER_MESSAGE_REQ"
export const ADMIN_SEND_BARBER_MESSAGE_SUCCESS = "ADMIN_SEND_BARBER_MESSAGE_SUCCESS"
export const ADMIN_SEND_BARBER_MESSAGE_FAIL = "ADMIN_SEND_BARBER_MAIL_FAIL"

export const ADMIN_UPDATE_PASSWORD_REQ = "ADMIN_UPDATE_PASSWORD_REQ"
export const ADMIN_UPDATE_PASSWORD_SUCCESS = "ADMIN_UPDATE_PASSWORD_SUCCESS"
export const ADMIN_UPDATE_PASSWORD_FAIL = "ADMIN_UPDATE_PASSWORD_FAIL"


export const GET_QUEUE_HISTORY_REQ = "GET_QUEUE_HISTORY_REQ"
export const GET_QUEUE_HISTORY_SUCCESS = "GET_QUEUE_HISTORY_SUCCESS"
export const GET_QUEUE_HISTORY_FAIL = "GET_QUEUE_HISTORY_FAIL"

export const GET_APPOINTMENT_HISTORY_REQ = "GET_APPOINTMENT_HISTORY_REQ"
export const GET_APPOINTMENT_HISTORY_SUCCESS = "GET_APPOINTMENT_HISTORY_SUCCESS"
export const GET_APPOINTMENT_HISTORY_FAIL = "GET_APPOINTMENT_HISTORY_FAIL"


export const GET_ALL_SALON_CATEGORIES_REQ = "GET_ALL_SALON_CATEGORIES_REQ"
export const GET_ALL_SALON_CATEGORIES_SUCCESS = "GET_ALL_SALON_CATEGORIES_SUCCESS"
export const GET_ALL_SALON_CATEGORIES_FAIL = "GET_ALL_SALON_CATEGORIES_FAIL"

export const GET_ALL_APPOINTMENTSLIST_REQ = "GET_ALL_APPOINTMENTSLIST_REQ"
export const GET_ALL_APPOINTMENTSLIST_SUCCESS = "GET_ALL_APPOINTMENTSLIST_SUCCESS"
export const GET_ALL_APPOINTMENTSLIST_FAIL = "GET_ALL_APPOINTMENTSLIST_FAIL"
export const GET_APPOINTMENTSLIST_BY_BARBERNAME = "GET_APPOINTMENTSLIST_BY_BARBERNAME"
export const CLEAR_ALL_APPOINTMENTSLIST = "CLEAR_ALL_APPOINTMENTSLIST"